services:
  - type: web
    name: my-frontend
    env: static
    branch: main
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: VITE_API_URL
        value:"https://post-page-rzna.onrender.com"