services:
  - type: static
    name: my-frontend
    env: static
    branch: main
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"  # Change this to 'dist'
    routes:
      - type: rewrite
        source: /.*  # Redirect all paths to index.html for React Router to handle
        destination: /index.html
    headers:
      - path: /*  # Optional Cache-Control header if needed
        name: Cache-Control
        value: no-cache
    envVars:
      - key: VITE_API_URL
        value: "https://post-page-rzna.onrender.com"
