services:
  - type: web
    name: my-frontend
    env: static
    branch: main
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: VITE_API_URL
        value: "https://post-page-rzna.onrender.com"
